# Generated by Django 4.2.3 on 2023-07-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان پیام')),
                ('fullname', models.CharField(max_length=300, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('message', models.TextField(max_length=40000, verbose_name='متن پیام')),
                ('date', models.DateField(auto_now_add=True, verbose_name='')),
                ('View_Message', models.BooleanField(default=False, null=True, verbose_name='تاریخ پیام')),
                ('message_admin_answer', models.TextField(max_length=30000, verbose_name='پاسخ ادمین')),
            ],
            options={
                'verbose_name': 'پیام ها',
                'verbose_name_plural': 'تماس با ما',
            },
        ),
    ]
