# Generated by Django 4.2.3 on 2023-07-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0002_alter_contactusmodel_view_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusmodel',
            name='View_Message',
            field=models.BooleanField(default=False, null=True, verbose_name='پیام دیده شده /پیام دیده نشده'),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ پیام'),
        ),
    ]
