# Generated by Django 4.2.3 on 2023-07-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps_upload_file',
            name='file',
            field=models.FileField(upload_to='imagess'),
        ),
    ]
