# Generated by Django 4.2.3 on 2023-07-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_module', '0002_alter_apps_upload_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps_upload_file',
            name='file',
            field=models.ImageField(upload_to='images'),
        ),
    ]
